// Generated by https://quicktype.io
export interface FormattedNewReleases {
  id: string;
  images: Image[];
  name: string;
  artists: Artist[];
  type: string;
}

export interface APINewReleases {
  albums: Albums;
}
export interface Albums {
  href: string;
  items: NewReleasesItem[];
  limit: number;
  next: string;
  offset: number;
  previous: null;
  total: number;
}

export interface NewRelease {
  message: string;
  playlists: Playlists;
}

export interface Playlists {
  href: string;
  items: NewReleasesItem[];
  limit: number;
  next: null;
  offset: number;
  previous: null;
  total: number;
}

export interface NewReleasesItem {
  album_type: 'album' | 'single';
  collaborative: boolean;
  artists: Artist[];
  description: string;
  external_urls: ExternalUrls;
  href: string;
  id: string;
  images: Image[];
  name: string;
  owner: Owner;
  primary_color: null;
  public: null;
  snapshot_id: string;
  tracks: Tracks;
  type: ItemType;
  uri: string;
}
export interface Artist {
  external_urls: ExternalUrls;
  href: string;
  id: string;
  name: string;
  type: ArtistType;
  uri: string;
  images: Image[];
}

export interface ExternalUrls {
  spotify: string;
}
export enum ArtistType {
  Artist = 'artist',
}
export interface Image {
  height: null;
  url: string;
  width: null;
}

export interface Owner {
  display_name: DisplayName;
  external_urls: ExternalUrls;
  href: string;
  id: ID;
  type: OwnerType;
  uri: URI;
}

export enum DisplayName {
  Spotify = 'Spotify',
}

export enum ID {
  Spotify = 'spotify',
}

export enum OwnerType {
  User = 'user',
}

export enum URI {
  SpotifyUserSpotify = 'spotify:user:spotify',
}

export interface Tracks {
  href: string;
  total: number;
}

export enum ItemType {
  Playlist = 'playlist',
}
